name: Publish CLI to NPM (Release)
on:
  release:
    types: [published]
env:
  NODE_VERSION: 22.x
permissions:
  id-token: write # Required for OIDC authentication
  contents: read
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Update to latest npm version
        run: npm i -g npm@latest
      - name: Check version correctness
        env:
          GITHUB_REF: ${{ github.ref }}
        run: |
          PACKAGE_VERSION=v$(npm --prefix=src/connector-cli pkg get version | tr -d '"')
          TAG_VERSION=${GITHUB_REF#refs/tags/}

          if [ "$PACKAGE_VERSION" = "$TAG_VERSION" ]; then
              echo "The package.json version matches the tag version."
          else
              echo "The package.json version does not match the tag version."
              echo "package.json version: $PACKAGE_VERSION"
              echo "Tag version: $TAG_VERSION"
              exit 1
          fi
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn run build-cli
      - name: Configure npm registry for scoped package
        run: |
          npm config set @chili-publish:registry https://registry.npmjs.org/
      - name: Publish
        working-directory: src/connector-cli
        run: npm publish --access=public --tag=latest
